package com.logossystemsit.logiceducore.shared.errors;

public enum ErrorCode {

    // Auth
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_ACCESS_DENIED,

    // Users
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_INACTIVE,
    USER_BLOCKED,
    USER_DUPLICATE_EMAIL,
    USER_DUPLICATE_DOCUMENT,

    // Schools
    SCHOOL_NOT_FOUND,
    SCHOOL_ALREADY_EXISTS,
    SCHOOL_INACTIVE,
    SCHOOL_HAS_ACTIVE_BRANCHES,

    // Branches
    BRANCH_NOT_FOUND,
    BRANCH_ALREADY_EXISTS,
    BRANCH_INACTIVE,
    BRANCH_MAIN_ALREADY_EXISTS,

    // Memberships
    MEMBERSHIP_NOT_FOUND,
    MEMBERSHIP_ALREADY_EXISTS,
    MEMBERSHIP_LAST_ACTIVE,
    MEMBERSHIP_ROLE_SCOPE_MISMATCH,

    // Academic Structure
    ACADEMIC_STRUCTURE_NOT_FOUND,
    ACADEMIC_LEVEL_NOT_FOUND,
    ACADEMIC_PERIOD_NOT_FOUND,
    ACADEMIC_PERIOD_OVERLAP,
    EVALUATION_PERIOD_NOT_FOUND,

    // Subjects
    SUBJECT_NOT_FOUND,
    SUBJECT_ALREADY_EXISTS,

    // Groups
    GROUP_NOT_FOUND,
    GROUP_ALREADY_EXISTS,
    GROUP_INACTIVE,
    GROUP_CAPACITY_EXCEEDED,
    GROUP_CAPACITY_CHANGED,

    // Enrollments
    ENROLLMENT_NOT_FOUND,
    ENROLLMENT_ALREADY_EXISTS,
    ENROLLMENT_SAME_SUBJECT_PERIOD,

    // Attendance
    ATTENDANCE_NOT_FOUND,
    ATTENDANCE_ALREADY_EXISTS,

    // Assessments
    ASSESSMENT_NOT_FOUND,
    ASSESSMENT_ALREADY_EXISTS,
    ASSESSMENT_HAS_GRADES,

    // Grades
    GRADE_NOT_FOUND,
    GRADE_ALREADY_EXISTS,
    GRADE_EXCEEDS_MAX_SCORE,

    // Generic
    VALIDATION_ERROR,
    BUSINESS_RULE_VIOLATION,
    INTERNAL_SERVER_ERROR,
    TEACHER_NOT_ASSIGNED
}
